sudo: true
dist: xenial
cache: pip
language: python
python:
    - "3.7"
install:
    - pip install -r requirements.txt

script:
    - coverage run -m unittest app/tests/tests_users.py -v
    - coverage run -a -m unittest app/tests/tests_users.py -v
    - coverage run -a -m unittest app/tests/tests_errors.py -v
    - coverage run -a -m unittest app/tests/tests_posts.py -v
    - codecov

#Send a payload to discord webhook url --> $WEBHOOK_URL
after_success:
    - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
    - chmod +x send.sh
    - ./send.sh success $WEBHOOK_URL

after_failure:
    - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
    - chmod +x send.sh
    - ./send.sh failure $WEBHOOK_URL
